# Generated by Django 4.1.7 on 2023-05-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    Initial=True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(max_length=7, unique=True)),
            ],
        ),
        
    ]
