# Generated by Django 4.1.7 on 2023-05-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    
    dependencies = [
        ('Ccombinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('annee_fabrication', models.IntegerField()),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ccombinations.marque')),
            ],
        ),
        migrations.CreateModel(
            name='FormulePeinture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_teint1', models.CharField(max_length=50)),
                ('quantite_base_teint1', models.FloatField()),
                ('base_teint2', models.CharField(blank=True, max_length=50, null=True)),
                ('quantite_base_teint2', models.FloatField(blank=True, null=True)),
                ('base_teint3', models.CharField(blank=True, max_length=50, null=True)),
                ('quantite_base_teint3', models.FloatField(blank=True, null=True)),
                ('code_couleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ccombinations.color')),
            ],
        ),
    ]
