# Generated by Django 4.1.7 on 2023-05-06 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ccombinations', '0002_marque_voiture_formulepeinture'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='code',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Ccombinations.color'),
            preserve_default=False,
        ),
    ]
