# Generated by Django 4.1.7 on 2023-05-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ccombinations', '0003_voiture_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='code',
        ),
        migrations.AddField(
            model_name='voiture',
            name='code',
            field=models.ManyToManyField(related_name='voitures', to='Ccombinations.color'),
        ),
    ]
